name: Node.js CI

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          
      - name: Install dependencies
        run: yarn install --force
        
      - run: git config user.name "John Koestner" && git config user.email "john.koestner@outlook.com"
        
      - name: Deploy
        run: yarn run deploy