name: Node.js CI

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: setup git config
        run: |
          git config --global user.name "John Koestner"
          git config --global user.email "johnkoestner@outlook.com"

      - name: gatsby cli
        run: npm install -g gatsby-cli

      - name: Set Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          
      - name: Install dependencies
        run: yarn install --force
        
      - name: Deploy
        run: yarn run deploy